### PR TITLE
Pull latest Flowmill agents by default

### PR DESCRIPTION
**Pull request by cirego**
We now tag our latest stable agent release using the 'latest' tag in our image
registry. Default to pulling the latest image to simplify our Helm
charts.

Override these tags in your "flowmill.yaml" file if you prefer to use a
pinned version.

---
This change is [Reviewable](https://reviewable.io/reviews/flowmill/flowmill-k8s/15)

### CODE REVIEW

**Comment by yonch** [comment]
How does this interact with ImagePullPolicy? We should be IfNotPresent -- does this force us to Always? (not sure if I remember the naming of the policies)

**Comment by cirego** [comment]
> How does this interact with ImagePullPolicy? We should be IfNotPresent -- does this force us to Always? (not sure if I remember the naming of the policies)

That's a great question. We should remove the `IfNotPresent` tag to insure that we always pull latest. This falls under the "omit imagePullPolicy and specify a tag with `:latest`" section in this doc: https://kubernetes.io/docs/concepts/containers/images/

**Comment by yonch** [comment]
Cool, you'll adjust that?

Also, customers seem to be split between wanting stability and wanting latest. I remember Twilio was allergic to automatic updates. Can we make this a feature flag in helm? e.g., `useLatest: false` would disable, and we'll include a `useLatest: true` in the `flowmill.yaml`, with documentation of the implications, so each customer can customize

**Comment by juchem** [comment]
I was just talking to @kerzner about something like this. Latest has an overloaded meaning in Docker so we should avoid it. But a custom tag like `stable` does seem like a good idea. This would lead to some level of "auto upgrade" as well, which although not in the ideal form, is desirable.

**Comment by cirego** [comment]
Since there appears to be some discussion on this, I'm going to shelve this PR until we can all discuss.

I'm going to open a new PR using the versions of the Agents we released today.

**Pull request closed without merging**
